### ISSUE TITLE
[FEAT] 상태관리 라이브러리 zustand -> redux, redux/toolkit

### ISSUE THREAD

**Issue by JunYoungKr** [Central-MakeUs/suppin-web#11]
## 기능 설명
- 상태관리 라이브러리를 zustand에서 기존에 사용하기로 했던 redux로 교체

## 환경

```shell
- "react-redux": "^9.1.2",
- "@reduxjs/toolkit": "^2.2.6",
```

**Comment by joseph0926** [comment]
리덕스 세팅하시는군요

혹시 노션 테스크 중에 리덕스 테스크 준영님으로 할당해주실수있으실까요?

**Comment by JunYoungKr** [comment]
> 리덕스 세팅하시는군요
> 
> 혹시 노션 테스크 중에 리덕스 테스크 준영님으로 할당해주실수있으실까요?

넵 알겠습니다 :)
